export const BACKGROUND = "#141a26"
export const BLUE_FANCY = "#2547F5"
export const GRAY_TEXT = "#ebebeb"
export const WHITE = "white"
export const GRAY_GUAPO = "#383838"
export const BLACK = "#38b5eb"
export const DANGER = "#FA7840"